### ISSUE TITLE
如果Start后，我想增加或者删除symbol如何做呢？

### ISSUE THREAD

**Issue by 4ever911** [Emptyset110/SinaL2#1]
比如， 

sina_l2 = SinaL2(symbols=["sz000001"], on_recv_data = on_recv_data)
sina_l2.start()

然后，我现在不想监听这个了，我想换成另外一个 symbollist

目前，好像没有看到接口来处理这个事情。

**Comment by Emptyset110** [comment]
@4ever911 你说得对。

先说一下现在是怎么实现的：每个websocket连接前需要请求一个token，请求这个token时需要递交请求订阅的内容，一个请求里最多只能有64个，所以会对请求自动做切割。所以做这个接口的时候考虑的业务内容里不存在“随时变更订阅内容”，因为设计时候的场景是一次订阅几百上千个，全天监听的。

因此对于你这个需求，我认为就接口的完善度来讲是很有意义的，但是放到实际应用场景里并不实用——我如果一个ws里一次性是由60个股票的行情，我仅仅不需要其中10个股票的行情，想换成另外10个，这在原则上不可能实现，因为一个token对应的list是固定的。但是你完全可以通过再实例化一个SinaL2，来新增你的订阅。

在dHydra的架构中也是这样，这是SinaL2的接口，另外有一些进程Worker专门实例化SinaL2，如果你需要取消一些，换成另一些，那很容易，关闭其中不需要的Worker，新建你需要的Worker就行。因此在我个人的实践中，订阅与取消订阅的开关没有必要做在SinaL2的接口中。

如果一定要在同一个SinaL2中去实现你说的取消订阅，我认为是可以的（我最近没有太多时间来做这个事情，会有小点麻烦，需要去管理每个ws里有哪些symbol，取消了某个symbol时候一般是不会去停止整个ws的吧，需要等一个ws里订阅的所有的symbol都取消了，才关闭整个ws，这样有没有觉得舍近求远了？）。但是要在同一个SinaL2中实现增加订阅，这会变得难以实现。因为目前几十个ws连接是以单线程异步协程实现的（就是说几十个ws开启以后是阻塞等待这几十个协程的），不可能往这个loop里添加协程。

不知道你能不能理解我的意思，有没有什么建议……

**Comment by 4ever911** [comment]
明白你的意思, 那目前看,现在也只能这样处理. 不知道你是否实验过, 最多一次可以订阅多少个symbol?

另外, 有两个问题:

1我看里面还有一个类是Sina, 我调用这个类去取沪深两市所有股票列表时,显是出错. 基本上,那个类的所有方法都调用失败.

å2. 刚学Python,以前都用C++有delete析构,Python如何取消掉当前的订阅, 比如client = Sina2(...),     用完了后, client = None就会自动关掉里面的websocket吗?

BTW: 感谢提供这样的一个库.

**Comment by Emptyset110** [comment]
@4ever911 额，第一点那应该是新浪屏蔽了你的网段ip，比如阿里云的一些网段，还有非电信的我也不清楚。刚才我本地测试了是可以的。
2. 听说python的del与c++的delete完全不同。据我听说/以及自己以前的实现方式：python的threading.Thread都是指向的函数运行完以后这个线程就结束了（我猜测python自己会清理内存）... 或许我应该看一下代码，在里头加个函数和bool变量，然后把164行的`while True`替换掉（不过我现在在外地……）
这个issue开着，解决完再关……

**Comment by Emptyset110** [comment]
@4ever911 对于一次能订阅多少个，我感觉新浪目前没做限制。3000+个也尝试过（包括一些指数还有分级基金之类）
