### ISSUE TITLE
Cannot get all stock list of the whole market

### ISSUE THREAD

**Issue by 4ever911** [Emptyset110/SinaL2#3]
I want to monitor the whole market, so I set Symbols=None.

But I get timeout error messages (get_today_all). Could you please take a look?

**Comment by Emptyset110** [comment]
@4ever911 There are two possibilities: 
1. Your ip address is banned by the sina server
2. (Most Likely) The purpose of `sina.get_today_all` is ambiguous. When it's first written, I tried to use it to get the real time quotation, so I set a timeout of 3 seconds, which (in my network condition) worked fine. However, this method is soon replaced by another faster method: `sina.get_realtime_quotes`. When I call `sina.get_symbols`, it simply calls `sina.get_today_all` once, and fetch the symbol column.
So ... I guess your problem could be resolved if you extend your tolerance of timeout. Try setting `timeout=5`, or even remove it.
The following code is in `Sina.py`. Good luck, and if it works for you, I would be appreciated if you could submit a Pull Request. I agree that the `timeout` is totally unnecessary here.

``` python
        retry = True
        while retry:
            try:
                response = self.session.get(
                    URL_API_MARKET_CENTER_GETHQNODEDATA(node),
                    GET_TODAY_ALL,
                    timeout=3
                ).text
                retry = False
            except:
                print("获取数据超时，正在重试")
```

**Comment by cszhe** [comment]
I don't think it is a timeout issue. Change the above code as follows can simply solve the problem:

```
        try:
            response = self.session.get(
                URL_API_MARKET_CENTER_GETHQNODEDATA(node),
                headers=HEADERS_GET_TODAY_ALL,
                timeout=30
            ).text
            retry = False
        except Exception as e:
            print(e)
            print("获取数据超时，正在重试...")
```

**Comment by Emptyset110** [comment]
@cszhe ...dude ... you've set the tolerance of timeout to be 30 seconds... that works as expected.

**Comment by Emptyset110** [comment]
好吧，我把timeout设置大一点吧

**Comment by Emptyset110** [comment]
@cszhe 不好意思，我是不是打错了。。。

**Comment by Emptyset110** [comment]
@cszhe 抱歉。。。我在外头。。要不你帮我Pull request一下吧。。。

**Comment by cszhe** [comment]
从来没用过pull request，我学习一下哈。timeout=3在我的机器上也足够了。以防万一，给改成5吧。

**Comment by Emptyset110** [comment]
多谢@cszhe
@4ever911

**Comment by Emptyset110** [comment]
多谢@cszhe
@4ever911
