### ISSUE TITLE
strptime 比较消耗时间，用下面这个替换掉会快很多很多很多

### ISSUE THREAD

**Issue by 4ever911** [Emptyset110/SinaL2#5]
在监控整个市场时，几千只股票，strptime对性能的影响还是很大的，因为日期和时间字符串格式是固定的，用下面的函数替换会快好多倍。

"time":datetime(int(data[4][0:4]), int(data[4][5:7]), int(data[4][8:10]), int(data[3][0:2]), int(data[3][3:5]), int(data[3][6:8])),

**Comment by Emptyset110** [comment]
多谢。好久没看这个东西了。我待会儿更新一下

**Comment by Emptyset110** [comment]
已经修改。
