### ISSUE TITLE
能不能关闭掉log？

### ISSUE THREAD

**Issue by 4ever911** [Emptyset110/SinaL2#7]
SinaL2构造函数里面的use_logger传递False进去后，里面的判断逻辑有问题， 为false里面的self.logger 不初始化，后面用会出错。

但是不停的写文件，太费CPU和内存。一天的数据写下来，几个G！

还有一个问题， SinaL2模块有import dHydra 模块， 如果没有config.json也报错，而实际这边是用不到这个文件的。

BTW， 能不能整理下SinaL2的代码，重构一下，里面太多重复的代码，结构有点乱。

**Comment by Emptyset110** [comment]
看一下util.get_logger函数，传入特定的参数可以设置关掉文件输出的句柄。

是很乱……过段时间再改吧……最近太忙了- -
